export const CREATE_EVENT = 'CREATE_EVENT';
export const FETCH_CURREVENTS = 'FETCH_CURREVENTS';
export const FETCH_PASTEVENTS = 'FETCH_PASTEVENTS';
export const FETCH_EVENT = 'FETCH_EVENT';
export const DELETE_EVENT = 'DELETE_EVENT';
export const EDIT_EVENT = 'EDIT_EVENT';
export const ADMIN_LOGOUT = 'ADMIN_LOGOUT';
export const ADMIN_LOGIN = 'ADMIN_LOGIN';
export const MAILCHIMP_FIRST_NAME = 'MAILCHIMP_FIRST_NAME';
export const MAILCHIMP_SECOND_NAME = 'MAILCHIMP_SECOND_NAME';
export const MAILCHIMP_EMAIL = 'MAILCHIMP_EMAIL';
export const SEND_DETAILS_TO_MAILCHIMP_API = "SEND_DETAILS_TO_MAILCHIMP_API";

